# Exported from Render on 2026-09-29T20:23:58Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: bhusetu3
      runtime: docker
      repo: https://github.com/angwanibhumika-ux/bhusetu3
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
